var ALLs = [
  { id: 379, level: 'SSR', name: '不见岳' },
  { id: 378, level: 'SR', name: '迦楼罗' },
  { id: 377, level: 'SP', name: '梦寻山兔' },
  { id: 376, level: 'SSR', name: '铃彦姬' },
  { id: 373, level: 'SSR', name: '夜刀神' },
  { id: 372, level: 'SP', name: '因幡辉夜姬' },
  { id: 371, level: 'SR', name: '川猿' },
  { id: 370, level: 'SSR', name: '饭笥' },
  { id: 369, level: 'SSR', name: '食灵' },
  { id: 368, level: 'SR', name: '饴细工' },
  { id: 367, level: 'SP', name: '绘世花鸟卷' },
  { id: 366, level: 'SP', name: '空相面灵气' },
  { id: 365, level: 'SR', name: '入内雀' },
  { id: 364, level: 'SSR', name: '阿修罗' },
  { id: 363, level: 'SSR', name: '帝释天' },
  { id: 362, level: 'SP', name: '蝉冰雪女' },
  { id: 361, level: 'R', name: '垢尝' },
  { id: 360, level: 'SSR', name: '灶门祢豆子' },
  { id: 359, level: 'SSR', name: '灶门炭治郎' },
  { id: 358, level: 'SP', name: '夜溟彼岸花' },
  { id: 357, level: 'SP', name: '初翎山风' },
  { id: 356, level: 'SSR', name: '千姬' },
  { id: 355, level: 'SP', name: '麓铭大岳丸' },
  { id: 354, level: 'SP', name: '待宵姑获鸟' },
  { id: 353, level: 'SSR', name: '紧那罗' },
  { id: 352, level: 'SP', name: '缚骨清姬' },
  { id: 350, level: 'SR', name: '蝎女' },
  { id: 351, level: 'SSR', name: '铃鹿御前' },
  { id: 349, level: 'SR', name: '风狸' },
  { id: 348, level: 'SP', name: '浮世青行灯' },
  { id: 347, level: 'SSR', name: '缘结神' },
  { id: 345, level: 'SSR', name: '鬼童丸' },
  { id: 346, level: 'SP', name: '聆海金鱼姬' },
  { id: 344, level: 'SSR', name: '云外镜' },
  { id: 343, level: 'SP', name: '天剑韧心鬼切' },
  { id: 341, level: 'SP', name: '鬼王酒吞童子' },
  { id: 342, level: 'SR', name: '星熊童子' },
  { id: 340, level: 'SR', name: '纸舞' },
  { id: 338, level: 'SSR', name: '泷夜叉姬' },
  { id: 339, level: 'SP', name: '烬天玉藻前' },
  { id: 337, level: 'SSR', name: '黑崎一护' },
  { id: 336, level: 'SR', name: '朽木露琪亚' },
  { id: 334, level: 'SP', name: '骁浪荒川之主' },
  { id: 335, level: 'SR', name: '蟹姬' },
  { id: 333, level: 'SSR', name: '大岳丸' },
  { id: 332, level: 'SR', name: '久次良' },
  { id: 331, level: 'SP', name: '御怨般若' },
  { id: 329, level: 'SR', name: '海忍' },
  { id: 330, level: 'SSR', name: '不知火' },
  { id: 328, level: 'SP', name: '赤影妖刀姬' },
  { id: 327, level: 'SP', name: '苍风一目连' },
  { id: 326, level: 'SP', name: '稻荷神御馔津' },
  { id: 324, level: 'SR', name: '化鲸' },
  { id: 325, level: 'SSR', name: '八岐大蛇' },
  { id: 323, level: 'R', name: '天井下' },
  { id: 320, level: 'SR', name: '一反木绵' },
  { id: 321, level: 'SR', name: '入殓师' },
  { id: 322, level: 'SP', name: '炼狱茨木童子' },
  { id: 318, level: 'SR', name: '於菊虫' },
  { id: 319, level: 'SSR', name: '桔梗' },
  { id: 317, level: 'SR', name: '人面树' },
  { id: 316, level: 'SSR', name: '白藏主' },
  { id: 315, level: 'SP', name: '少羽大天狗' },
  { id: 312, level: 'SSR', name: '鬼切' },
  { id: 314, level: 'SSR', name: '杀生丸' },
  { id: 313, level: 'SSR', name: '犬夜叉' },
  { id: 311, level: 'SSR', name: '面灵气' },
  { id: 307, level: 'SR', name: '猫掌柜' },
  { id: 310, level: 'R', name: '蜜桃&芥子' },
  { id: 309, level: 'SR', name: '阿香' },
  { id: 308, level: 'SSR', name: '鬼灯' },
  { id: 305, level: 'SSR', name: '卖药郎' },
  { id: 294, level: 'SSR', name: '奴良陆生' },
  { id: 296, level: 'SSR', name: '山风' },
  { id: 298, level: 'SR', name: '薰' },
  { id: 306, level: 'R', name: '虫师' },
  { id: 302, level: 'R', name: '小袖之手' },
  { id: 303, level: 'SR', name: '弈' },
  { id: 304, level: 'SSR', name: '御馔津' },
  { id: 297, level: 'SR', name: '日和坊' },
  { id: 295, level: 'SR', name: '追月神' },
  { id: 301, level: 'R', name: '数珠' },
  { id: 300, level: 'SSR', name: '玉藻前' },
  { id: 293, level: 'SR', name: '百目鬼' },
  { id: 292, level: 'SSR', name: '雪童子' },
  { id: 291, level: 'SR', name: '书翁' },
  { id: 289, level: 'R', name: '兔丸' },
  { id: 290, level: 'SR', name: '小松丸' },
  { id: 288, level: 'SSR', name: '彼岸花' },
  { id: 287, level: 'SR', name: '匣中少女' },
  { id: 285, level: 'SR', name: '鸩' },
  { id: 286, level: 'SR', name: '以津真天' },
  { id: 283, level: 'SSR', name: '荒' },
  { id: 282, level: 'SR', name: '金鱼姬' },
  { id: 275, level: 'SR', name: '万年竹' },
  { id: 273, level: 'SR', name: '青坊主' },
  { id: 274, level: 'R', name: '古笼火' },
  { id: 276, level: 'SR', name: '夜叉' },
  { id: 277, level: 'SR', name: '黑童子' },
  { id: 278, level: 'SR', name: '白童子' },
  { id: 279, level: 'SSR', name: '花鸟卷' },
  { id: 281, level: 'SR', name: '烟烟罗' },
  { id: 280, level: 'SSR', name: '辉夜姬' },
  { id: 200, level: 'SR', name: '桃花妖' },
  { id: 201, level: 'SR', name: '雪女' },
  { id: 202, level: 'R', name: '三尾狐' },
  { id: 205, level: 'R', name: '座敷童子' },
  { id: 206, level: 'R', name: '鲤鱼精' },
  { id: 207, level: 'R', name: '九命猫' },
  { id: 208, level: 'R', name: '狸猫' },
  { id: 209, level: 'R', name: '河童' },
  { id: 210, level: 'SR', name: '鬼使白' },
  { id: 211, level: 'SR', name: '鬼使黑' },
  { id: 212, level: 'R', name: '童男' },
  { id: 213, level: 'R', name: '童女' },
  { id: 214, level: 'R', name: '饿鬼' },
  { id: 215, level: 'SR', name: '孟婆' },
  { id: 216, level: 'R', name: '巫蛊师' },
  { id: 217, level: 'SSR', name: '大天狗' },
  { id: 218, level: 'R', name: '鸦天狗' },
  { id: 219, level: 'SSR', name: '酒吞童子' },
  { id: 220, level: 'SR', name: '犬神' },
  { id: 221, level: 'R', name: '食发鬼' },
  { id: 222, level: 'R', name: '武士之灵' },
  { id: 223, level: 'SR', name: '骨女' },
  { id: 224, level: 'R', name: '雨女' },
  { id: 225, level: 'R', name: '跳跳弟弟' },
  { id: 226, level: 'R', name: '跳跳妹妹' },
  { id: 227, level: 'R', name: '兵俑' },
  { id: 228, level: 'R', name: '丑时之女' },
  { id: 230, level: 'R', name: '独眼小僧' },
  { id: 231, level: 'SR', name: '鬼女红叶' },
  { id: 232, level: 'R', name: '铁鼠' },
  { id: 233, level: 'SR', name: '跳跳哥哥' },
  { id: 234, level: 'R', name: '椒图' },
  { id: 236, level: 'R', name: '管狐' },
  { id: 237, level: 'R', name: '山兔' },
  { id: 238, level: 'R', name: '萤草' },
  { id: 241, level: 'R', name: '蝴蝶精' },
  { id: 242, level: 'SR', name: '傀儡师' },
  { id: 243, level: 'R', name: '山童' },
  { id: 244, level: 'R', name: '首无' },
  { id: 247, level: 'SR', name: '海坊主' },
  { id: 248, level: 'SSR', name: '荒川之主' },
  { id: 249, level: 'R', name: '觉' },
  { id: 250, level: 'R', name: '青蛙瓷器' },
  { id: 251, level: 'SR', name: '判官' },
  { id: 252, level: 'SR', name: '凤凰火' },
  { id: 253, level: 'SR', name: '吸血姬' },
  { id: 254, level: 'SR', name: '妖狐' },
  { id: 255, level: 'SSR', name: '阎魔' },
  { id: 256, level: 'SR', name: '妖琴师' },
  { id: 257, level: 'SR', name: '食梦貘' },
  { id: 258, level: 'SSR', name: '两面佛' },
  { id: 259, level: 'SSR', name: '小鹿男' },
  { id: 260, level: 'SR', name: '清姬' },
  { id: 261, level: 'SR', name: '镰鼬' },
  { id: 262, level: 'SR', name: '姑获鸟' },
  { id: 263, level: 'SR', name: '二口女' },
  { id: 264, level: 'SR', name: '白狼' },
  { id: 265, level: 'SSR', name: '茨木童子' },
  { id: 266, level: 'SSR', name: '青行灯' },
  { id: 267, level: 'SR', name: '樱花妖' },
  { id: 268, level: 'SR', name: '惠比寿' },
  { id: 269, level: 'SSR', name: '妖刀姬' },
  { id: 270, level: 'SR', name: '络新妇' },
  { id: 272, level: 'SSR', name: '一目连' },
  { id: 271, level: 'SR', name: '般若' }
]

var SPs = [
  { id: 377, name: "梦寻山兔" },
  { id: 372, name: "因幡辉夜姬" },
  { id: 367, name: "绘世花鸟卷" },
  { id: 366, name: "空相面灵气" },
  { id: 362, name: "蝉冰雪女" },
  { id: 358, name: "夜溟彼岸花" },
  { id: 357, name: "初翎山风" },
  { id: 355, name: "麓铭大岳丸" },
  { id: 354, name: "待宵姑获鸟" },
  { id: 352, name: "缚骨清姬" },
  { id: 348, name: "浮世青行灯" },
  { id: 346, name: "聆海金鱼姬" },
  { id: 343, name: "天剑韧心鬼切" },
  { id: 341, name: "鬼王酒吞童子" },
  { id: 339, name: "烬天玉藻前" },
  { id: 334, name: "骁浪荒川之主" },
  { id: 331, name: "御怨般若" },
  { id: 328, name: "赤影妖刀姬" },
  { id: 327, name: "苍风一目连" },
  { id: 326, name: "稻荷神御馔津" },
  { id: 322, name: "炼狱茨木童子" },
  { id: 315, name: "少羽大天狗" }
]

var SSRs = [
  { id: 379, name: "不见岳" },
  { id: 376, name: "铃彦姬" },
  { id: 373, name: "夜刀神" },
  { id: 370, name: "饭笥" },
  { id: 369, name: "食灵" },
  { id: 364, name: "阿修罗" },
  { id: 363, name: "帝释天" },
  { id: 360, name: "灶门祢豆子" },
  { id: 359, name: "灶门炭治郎" },
  { id: 356, name: "千姬" },
  { id: 353, name: "紧那罗" },
  { id: 351, name: "铃鹿御前" },
  { id: 347, name: "缘结神" },
  { id: 345, name: "鬼童丸" },
  { id: 344, name: "云外镜" },
  { id: 338, name: "泷夜叉姬" },
  { id: 337, name: "黑崎一护" },
  { id: 333, name: "大岳丸" },
  { id: 330, name: "不知火" },
  { id: 325, name: "八岐大蛇" },
  { id: 319, name: "桔梗" },
  { id: 316, name: "白藏主" },
  { id: 314, name: "杀生丸" },
  { id: 313, name: "犬夜叉" },
  { id: 312, name: "鬼切" },
  { id: 311, name: "面灵气" },
  { id: 308, name: "鬼灯" },
  { id: 305, name: "卖药郎" },
  { id: 304, name: "御馔津" },
  { id: 300, name: "玉藻前" },
  { id: 296, name: "山风" },
  { id: 294, name: "奴良陆生" },
  { id: 292, name: "雪童子" },
  { id: 288, name: "彼岸花" },
  { id: 283, name: "荒" },
  { id: 280, name: "辉夜姬" },
  { id: 279, name: "花鸟卷" },
  { id: 272, name: "一目连" },
  { id: 269, name: "妖刀姬" },
  { id: 266, name: "青行灯" },
  { id: 265, name: "茨木童子" },
  { id: 259, name: "小鹿男" },
  { id: 258, name: "两面佛" },
  { id: 255, name: "阎魔" },
  { id: 248, name: "荒川之主" },
  { id: 219, name: "酒吞童子" },
  { id: 217, name: "大天狗" }
]

var SRs = [
  { id: 378, name: "迦楼罗" },
  { id: 371, name: "川猿" },
  { id: 368, name: "饴细工" },
  { id: 365, name: "入内雀" },
  { id: 350, name: "蝎女" },
  { id: 349, name: "风狸" },
  { id: 342, name: "星熊童子" },
  { id: 340, name: "纸舞" },
  { id: 336, name: "朽木露琪亚" },
  { id: 335, name: "蟹姬" },
  { id: 332, name: "久次良" },
  { id: 329, name: "海忍" },
  { id: 324, name: "化鲸" },
  { id: 321, name: "入殓师" },
  { id: 320, name: "一反木绵" },
  { id: 318, name: "於菊虫" },
  { id: 317, name: "人面树" },
  { id: 309, name: "阿香" },
  { id: 307, name: "猫掌柜" },
  { id: 303, name: "弈" },
  { id: 298, name: "薰" },
  { id: 297, name: "日和坊" },
  { id: 295, name: "追月神" },
  { id: 293, name: "百目鬼" },
  { id: 291, name: "书翁" },
  { id: 290, name: "小松丸" },
  { id: 287, name: "匣中少女" },
  { id: 286, name: "以津真天" },
  { id: 285, name: "鸩" },
  { id: 282, name: "金鱼姬" },
  { id: 281, name: "烟烟罗" },
  { id: 278, name: "白童子" },
  { id: 277, name: "黑童子" },
  { id: 276, name: "夜叉" },
  { id: 275, name: "万年竹" },
  { id: 273, name: "青坊主" },
  { id: 271, name: "般若" },
  { id: 270, name: "络新妇" },
  { id: 268, name: "惠比寿" },
  { id: 267, name: "樱花妖" },
  { id: 264, name: "白狼" },
  { id: 263, name: "二口女" },
  { id: 262, name: "姑获鸟" },
  { id: 261, name: "镰鼬" },
  { id: 260, name: "清姬" },
  { id: 257, name: "食梦貘" },
  { id: 256, name: "妖琴师" },
  { id: 254, name: "妖狐" },
  { id: 253, name: "吸血姬" },
  { id: 252, name: "凤凰火" },
  { id: 251, name: "判官" },
  { id: 247, name: "海坊主" },
  { id: 242, name: "傀儡师" },
  { id: 233, name: "跳跳哥哥" },
  { id: 231, name: "鬼女红叶" },
  { id: 223, name: "骨女" },
  { id: 220, name: "犬神" },
  { id: 215, name: "孟婆" },
  { id: 211, name: "鬼使黑" },
  { id: 210, name: "鬼使白" },
  { id: 201, name: "雪女" },
  { id: 200, name: "桃花妖" }
]

var Rs = [
  { id: 361, name: "垢尝" },
  { id: 323, name: "天井下" },
  { id: 310, name: "蜜桃&芥子" },
  { id: 306, name: "虫师" },
  { id: 302, name: "小袖之手" },
  { id: 301, name: "数珠" },
  { id: 289, name: "兔丸" },
  { id: 274, name: "古笼火" },
  { id: 250, name: "青蛙瓷器" },
  { id: 249, name: "觉" },
  { id: 244, name: "首无" },
  { id: 243, name: "山童" },
  { id: 241, name: "蝴蝶精" },
  { id: 238, name: "萤草" },
  { id: 237, name: "山兔" },
  { id: 236, name: "管狐" },
  { id: 234, name: "椒图" },
  { id: 232, name: "铁鼠" },
  { id: 230, name: "独眼小僧" },
  { id: 228, name: "丑时之女" },
  { id: 227, name: "兵俑" },
  { id: 226, name: "跳跳妹妹" },
  { id: 225, name: "跳跳弟弟" },
  { id: 224, name: "雨女" },
  { id: 222, name: "武士之灵" },
  { id: 221, name: "食发鬼" },
  { id: 218, name: "鸦天狗" },
  { id: 216, name: "巫蛊师" },
  { id: 214, name: "饿鬼" },
  { id: 213, name: "童女" },
  { id: 212, name: "童男" },
  { id: 209, name: "河童" },
  { id: 208, name: "狸猫" },
  { id: 207, name: "九命猫" },
  { id: 206, name: "鲤鱼精" },
  { id: 205, name: "座敷童子" },
  { id: 202, name: "三尾狐" }
]

export {
  ALLs, SPs, SSRs, SRs, Rs
}